# Generated by Django 6.0.4 on 2026-06-15 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="freelancerprofile",
            name="skills",
        ),
        migrations.AddField(
            model_name="freelancerprofile",
            name="total_reviews",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name="Skill",
        ),
    ]
